DROP DATABASE IF EXISTS kionling_db;
CREATE DATABASE kionling_db;
USE kionling_db;
CREATE TABLE User (
    id INTEGER AUTO_INCREMENT,
    username VARCHAR(200),
    password VARCHAR(200),
    PRIMARY KEY (id)
);

CREATE TABLE Email (
id INTEGER AUTO_INCREMENT NOT NULL,
 title VARCHAR(200),
 message VARCHAR(200),
 PRIMARY KEY(id)
);